TILE_SIZE = 8

AGENT_RADIUS          = 6.0
PLANNER_RADIUS_MARGIN = 5.0
AGENT_BASE_SPEED      = 50.0

VELOCITY_SMOOTHING    = 0.25

EMOTION_DECAY                = -0.02
EMOTION_DELTA_HAZARD_CONTACT = +0.15
EMOTION_DELTA_HAZARD_VISIBLE = +0.08
EMOTION_DELTA_CONTAGION      = +0.04

CONTAGION_RADIUS        = 35.0
CONTAGION_RADIUS_HIGH_N = 20.0
N_CONTAGION_THRESHOLD   = 12
HAZARD_CONTAGION_PCTG   = 0.05

FSM_CALM_TO_EVACUATE  = 0.35
FSM_EVACUATE_TO_CALM  = 0.25
FSM_EVACUATE_TO_PANIC = 0.72
FSM_PANIC_TO_EVACUATE = 0.62

FSM_SPEED_CALM      = 1.00
FSM_SPEED_EVACUATE  = 1.15
FSM_SPEED_PANIC     = 1.30
FSM_SPEED_SMOOTHING = 0.20

FSM_CALM_VEL_SMOOTH  = 0.25
FSM_EVAC_VEL_SMOOTH  = 0.16
FSM_PANIC_VEL_SMOOTH = 0.10

HAZARD_VISION_RADIUS = 5 * TILE_SIZE
LOCAL_DENSITY_RADIUS = 35.0

ASTAR_HAZARD_COST     = 25.0
ASTAR_STUCK_THRESHOLD = 5

DQN_HIDDEN_DIM         = 128
DQN_BUFFER_CAPACITY    = 100_000
DQN_TRAIN_START_SIZE   = 2_000
DQN_BATCH_SIZE         = 64
DQN_GAMMA              = 0.99
DQN_LR                 = 1e-3
DQN_TARGET_UPDATE_FREQ = 300
DQN_EPSILON_START      = 1.0
DQN_EPSILON_END        = 0.05
DQN_EPSILON_DECAY      = 1_600_000
DQN_GRAD_CLIP_NORM     = 10.0
DQN_OBS_DIM            = 17

PER_ALPHA       = 0.6
PER_BETA_START  = 0.4
PER_BETA_FRAMES = 3_000_000

REWARD_PROGRESS_SCALE      =  60.0
REWARD_EVACUATED           =  80.0
REWARD_TIME_PENALTY        =  -0.05
REWARD_NO_PROGRESS         =  -1.5
REWARD_HAZARD_CONTACT      =  -3.0
REWARD_HAZARD_VISIBLE_CALM =   0.10
REWARD_HAZARD_PANIC        =  -0.1
REWARD_COLLISION           =   0.0
REWARD_DENSITY_SCALE       =  -0.1
REWARD_STAGNATION_STUCK      = -2.0
REWARD_STAGNATION_OSCILLATE  = -3.0

CURRICULUM_PROMOTION_THRESHOLD = 0.80
CURRICULUM_EVAL_WINDOW         = 30
CURRICULUM_PATIENCE            = 500
CURRICULUM_SAVE_EVERY          = 50
CURRICULUM_EARLY_PATIENCE_AFTER     = 250
CURRICULUM_EARLY_PATIENCE_THRESHOLD = 0.15

DQN_UPDATE_EVERY = 4